services:
  postgres:
    container_name: ${CONTAINER_NAME-lp}-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lp-db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: ${CONTAINER_NAME-lp}-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  minio:
    container_name: ${CONTAINER_NAME-lp}-minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: miniominio
      MINIO_ROOT_PASSWORD: miniominio
    ports:
      - "9222:9000"
      - "9001:9001"

  meilisearch:
    container_name: ${CONTAINER_NAME-lp}-meilisearch
    image: getmeili/meilisearch:latest
    ports:
      - 3331:3331
    volumes:
      - meilisearch_data:/data
    environment:
      MEILI_DB_PATH: "/meili_data/data.ms"
      MEILI_ENV: development
      MEILI_HTTP_ADDR: ":::3331"
      MEILI_MASTER_KEY: ooppk8bb3ibb85zpycpg3fcew23rgkwf
      PORT: 3331

volumes:
  postgres_data:
  redis_data:
  minio_data:
  meilisearch_data: