# FROM node:22

# ENV NODE_ENV=development

# WORKDIR /app

# # Use cache mount for faster npm install
# COPY package*.json ./
# RUN --mount=type=cache,target=/root/.npm \
#     npm install

# # Copy everything else (except what's in .dockerignore)
# COPY . .

# EXPOSE 9000

# CMD npm run ib && npm run dev