FROM node:22

ENV NODE_ENV=development

WORKDIR /app

# Use BuildKit's cache mount for faster npm install
COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm install

COPY . .

EXPOSE 8000

CMD ["npm", "run", "dev"]