FROM node:bookworm

# Create app directory
WORKDIR /app

COPY . /app

# Install system dependencies
# RUN apt-get update && \
#     apt-get install -y \
#     postgresql-client \
#     curl \
#     git \
#     gh \
#     && rm -rf /var/lib/apt/lists/*

# Update npm and install global packages
# RUN npm install -g npm@latest && \
#     npm install -g @medusajs/medusa-cli

CMD ["sleep", "infinity"]
