FROM node:bookworm

# Create app directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
    gh \
    git \
    bat \
    curl \
    micro \
    pkg-config \
    libssl-dev \
    build-essential \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Install Nushell
RUN curl -LO https://github.com/nushell/nushell/releases/download/0.102.0/nu-0.102.0-x86_64-unknown-linux-gnu.tar.gz && \
    tar -xzf nu-0.102.0-x86_64-unknown-linux-gnu.tar.gz && \
    mv nu-0.102.0-x86_64-unknown-linux-gnu/nu /usr/local/bin/ && \
    rm -rf nu-0.102.0-x86_64-unknown-linux-gnu*

# Install Oh My Zsh plugins ( must be added in .zshrc plugins(...))
RUN git clone https://github.com/zsh-users/zsh-autosuggestions.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting && \
    git clone https://github.com/MichaelAquilina/zsh-you-should-use.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/you-should-use

# Install global npm packages 
RUN npm install -g npm@latest && \
    npm install -g @medusajs/medusa-cli && \
    npm install -g better-commits

# Copy application files LAST
COPY . /app

CMD ["sleep", "infinity"]
